# Generated by Django 3.0.4 on 2020-03-10 21:46
import django
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_file', models.FileField(upload_to='uploaded/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='EncodedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoded_file', models.FileField(upload_to='encoded')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.RawFile')),
                ('encryption_key', models.fields.TextField()),
                ('encryption_kid', models.fields.TextField()),
            ],
        ),
    ]
