# Generated by Django 3.0.5 on 2020-05-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encodedfile',
            name='status',
            field=models.TextField(choices=[('init', 'initiated'), ('ended', 'finished')], default='init'),
        ),
    ]
