# Generated by Django 3.0.5 on 2020-05-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_encodedfile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encodedfile',
            name='status',
            field=models.TextField(choices=[('init', 'initiated'), ('ended', 'finished'), ('failed', 'failed')], default='init'),
        ),
    ]
