# Generated by Django 3.0.5 on 2020-05-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200501_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encodedfile',
            name='encoded_file',
            field=models.FileField(upload_to=''),
        ),
    ]
